services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./todo-application-backend/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - todo-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Spring Boot Backend Application
  backend:
    build:
      context: ./todo-application-backend
      dockerfile: Dockerfile
    container_name: todo-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: todo_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
      LOG_DIR: /app/logs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - todo-network

  # Next.js Frontend Application
  frontend:
    build:
      context: ./todo-appilication-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8081/api/V1
    container_name: todo-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8081/api/V1
      NODE_ENV: production
    depends_on:
      - backend
    networks:
      - todo-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: todo-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: todo_user
      PMA_PASSWORD: todo_password
    depends_on:
      - mysql
    networks:
      - todo-network

volumes:
  mysql_data:
    driver: local

networks:
  todo-network:
    driver: bridge
